### ISSUE TITLE
Add start/end date to database

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-api#110]
1. Update the Prisma schema to include `start_date` and `end_date` for the `Event` model.
2. Update `Event` and `Booper` to be many-to-many (An array on both of them of each other)

```mermaid
erDiagram
    Event {
        DateTime start_date
        DateTime end_date
    }
    Booper {
    }
    Event }o--o{ Booper: EventBoopers
```

**Comment by daylieveryday** [comment]
All done :)

![Image](https://github.com/CreativeSolutionsGroup/smart-events-api/assets/117611535/a24aecb1-dc26-4e7e-93de-fb7cdaae4e7a)
